CREATE DATABASE IF NOT EXISTS qlbhcchqa;
USE qlbhcchqa;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  size VARCHAR(20),
  color VARCHAR(30),
  price DECIMAL(10, 2),
  quantity INT,
  category VARCHAR(100),
  imageUrl TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);